export const TermsAndConditions = [
    "A deposit of 80% Is to be Paid to secure an appointment",
    "Full payment is due on or before the session date",
    "Travel fees may apply for session outside LAGOS/NIGERIA hours in advance",
    "Rescheduling or cancellation must be at least 48 hours in advance",
    "The photographer retains the copyright to all images but grants the client personal usage rights",
    "Balance payable immediately after the shoot",
    "EDITS TAKE 5-7 WORKING DAYS (AFTER SELECTIONS) DEPENDING ON THE NUMBER OF DELIVERIES",
    "EXPRESS DELIVERY (turn out time 24 hrs - NGN 50,000) (48hrs - NGN 30,000)",
    "EXTRA EDIT IS NGN20,000 PER IMAGE",
    "DELAY FEE is 10,000 after every hour",
    "OUTDOOR/LOCATION SHOOT requires a logistics fee of (NGN40,000)",
    "Additional individual in the Frame in any of these sessions is plus N35,000 & 1 additional edited image deliverable",
    "CONSULTATION FEE - NGN30,000 (creating direction/mood board)",
    "SET DESIGN COST NGN100,000 - NGN150,000 (depending on the convolution of the set)",
    "FOR SESSIONS OUTSIDE LAGOS, CLIENTS MUST TAKE CARE OF ROUNDTRIP FARE (LOGISTICS) AND HOTEL RESERVATIONS FOR THE TEAM.",
    "NO REFUND",
    "From 10 pm, midnight session attracts an extra fee NGN30,000",
]
